openapi: 3.0.3
info:
  title: ChainSafe Marketplace API
  contact:
    email: info@chainsafe.io
    name: ChainSafe
    url: https://dashboard.gaming.chainsafe.io/
  version: 1.19.2
externalDocs:
  description: Find out more about ChainSafe
  url: "https://doc.chainsafe.io"
servers:
  - url: "https://game-api-stg.chainsafe.io"
    description: STAGING
  - url: "https://api.gaming.chainsafe.io"
    description: PRODUCTION
tags:
  - name: Items
    description: This section lists all the APIs related to marketplace items.
paths:
  /v1/projects/{projectID}/items:
    $ref: 'paths/get_project_items.yaml'
  /v1/projects/{projectID}/marketplaces/{marketplaceID}/items:
    $ref: 'paths/get_project_marketplace_items.yaml'
  /v1/projects/{projectID}/marketplaces/{marketplaceID}/items/{itemID}:
    $ref: 'paths/get_project_marketplace_item.yaml'