on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a buld step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          projectName: game-docs-v2
          directory: /build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
