name: publish
on:
  workflow_run:
    workflows:
      - check
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Chekout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          projectName: game-docs-v2
          directory: build/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
